version: "3"
services:
  db:
    image: postgres
    env-file:
      - config/database/postgres.env
      
  
  backend:
    build: ./src/backend
    image: backend_labsadmin
    command: gunicorn labsadmin.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - .src/backend:/app/
    ports:
       - "8080:8080"
    env-file:
      - config/backend.env
      
