version: "3"
services:

  backend:
    build: 
      context: ./src/backend/
      dockerfile: develop.Dockerfile
    image: backend_labsadmin
    volumes:
      - ./src/backend:/app/
    ports:
      - "8000:8000"
