version: "3"
services:

  redis:
    image: "redis:alpine"
  backend:
    build: 
      context: ./src/backend/
      dockerfile: develop.Dockerfile
    image: backend_labsadmin
    volumes:
      - ./src/backend:/app/
    ports:
      - "8000:8000"
    environment:
      REDIS_URL: redis
      REDIS_PORT: 6379